#!/bin/sh

# sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a emacs desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar topbar &>/dev/null &

compton &>/dev/null &

${HOME}/bin/pimp_my_gui.bash &>/dev/null &
