#!/bin/sh

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a Xdialog manage=off

pgrep -u "${USER}" polybar &>/dev/null || nice -n 9 polybar topbar &>/dev/null &

pgrep -u "${USER}" compton &>/dev/null || nice -n 9 compton &>/dev/null &

${HOME}/bin/pimp_my_gui.bash &> /dev/null &
