#!/bin/sh
#
# /etc/cron.monthly/monthly_maint
# script to run monthly maintenance tasks

MS="/home/paperjam/sbin/monthly"
if [ -d "${MS}" ]; then
    for SCPT in "${MS}"/*; do
        "${SCPT}"
    done
fi
