#!/bin/sh
#
# /etc/cron.weekly/weekly_maint
# script to run weekly maintenance tasks

WS="/home/paperjam/sbin/weekly"
if [ -d "${WS}" ]; then
    for SCPT in "${WS}"/*; do
        "${SCPT}"
    done
fi
