#!/bin/sh
#
# /etc/cron.daily/daily_maint
# script to run daily maintenance tasks

DS="/home/paperjam/sbin/cronjobs/daily"
if [ -d "${DS}" ]; then
    cd "${DS}"
    for SCPT in ./*; do
        "${SCPT}"
    done
fi
