#!/bin/sh
#
# /etc/cron.daily/daily_maint
# script to run daily maintenance tasks

SDN="$(dirname "$(realpath $0)")"
DS="${SDN}/daily"
if [ -d "${DS}" ]; then
    for SCPT in "${DS}/"*.bash; do
        "${SCPT}"
    done
fi
