#!/bin/sh
#
# /etc/cron.monthly/monthly_maint
# script to run monthly maintenance tasks

MS="/home/paperjam/sbin/cronjobs/monthly"
if [ -d "${MS}" ]; then
    cd "${MS}"
    for SCPT in ./*; do
        "${SCPT}"
    done
fi
