#!/bin/sh
#
# /etc/cron.monthly/monthly_maint
# script to run monthly maintenance tasks

SDN="$(dirname $(realpath $0))"
MS="${SDN}/monthly"
if [ -d "${MS}" ]; then
    cd "${MS}"
    for SCPT in ./*; do
        "${SCPT}"
    done
fi
