#!/bin/sh
#
# /etc/cron.weekly/weekly_maint
# script to run weekly maintenance tasks

WS="/home/paperjam/sbin/cronjobs/weekly"
if [ -d "${WS}" ]; then
    cd "${WS}"
    for SCPT in ./*; do
        "${SCPT}"
    done
fi
