#!/bin/sh
#
# /etc/cron.weekly/weekly_maint
# script to run weekly maintenance tasks

SDN="$(dirname $(realpath $0))"
WS="${SDN}/weekly"
if [ -d "${WS}" ]; then
    for SCPT in "${WS}/"*\.bash; do
        "${SCPT}"
    done
fi
